#!/usr/bin/env ruby

# Source: https://github.com/cmur2/munin-openweather

# Example usage:
#  Do
#    ln -s /path/to/openweather_ openweather_<type>_<id>
#  where <type> is currently ignored (formerly one of
#  [station, weather]) and <id> is a suitable
#  city id from http://openweathermap.org/
#  These parameters translate directly into a URL formed like this:
#    http://openweathermap.org/data/<api>/weather?id=<id>
#
# Example config:
#  [openweather_*]
#

require 'rubygems'
require 'json'

require 'open-uri'

KELVIN_BIAS = 273.15
SYMLINK_COMPAT = true

script = File.basename($0)
@entity_type, @entity_id = script.gsub('openweather_', '').split('_')
@cmd = ARGV[0]

# open stderr
$stderr = IO.new(2, "w")

def uri(entity_type, entity_id)
	entity_type = "city" if entity_type == "weather" and SYMLINK_COMPAT
	"http://openweathermap.org/data/2.5/weather?id=#{entity_id}"
end

def echo_weather(station_id, name, temp)
	case @cmd
	when 'config'
		puts "graph_title Temperature at #{name}"
		puts "graph_args --lower-limit 0"
		puts "graph_vlabel Celsius"
		puts "graph_category weather"
		puts "graph_scale no"
		puts "graph_info This graph show the temperature at #{name}"
		puts "temperature.label temperature"
		puts "temperature.info Temperature in degree Celsius"
		puts "temperature.type GAUGE"
	else
		puts "temperature.value #{temp}"
	end
end

begin
	raw_data = open(uri(@entity_type, @entity_id)).read
	data = JSON.parse(raw_data)
	#puts data.inspect
	echo_weather(data['id'], data['name'], data['main']['temp']-KELVIN_BIAS)
rescue => ex
	$stderr.puts "Cannot connect to openweathermap.org: #{ex.to_s}"
end
