#!/usr/bin/env ruby

# Source: https://github.com/cmur2/munin-openweather

# Example usage:
#  Do
#    ln -s /path/to/openweather_ openweather_<type>_<id>
#  where <type> is one of [station, weather] and <id> is a suitable
#  station or city id from http://openweathermap.org/
#  These parameters translate directly into a URL formed like this:
#    http://openweathermap.org/data/<type>/<id>?type=json
#
# Example config:
#  [openweather_*]
#

require 'rubygems'
require 'json'

require 'open-uri'

KELVIN_BIAS = 273.15

script = File.basename($0)
@entity_type, @entity_id = script.gsub('openweather_', '').split('_')
@cmd = ARGV[0]

# open stderr
$stderr = IO.new(2, "w")

def uri(entity_type, entity_id)
	"http://openweathermap.org/data/2.0/weather/#{entity_type}/#{entity_id}?type=json"
end

raw_data = open(uri(@entity_type, @entity_id)).read
data = JSON.parse(raw_data)

#puts data.inspect

def echo_weather(station_id, name, temp)
	case @cmd
	when 'config'
		puts "graph_title Temperature at #{name}"
		puts "graph_args --lower-limit 0"
		puts "graph_vlabel Celsius"
		puts "graph_category weather"
		puts "graph_scale no"
		puts "graph_info This graph show the temperature at #{name}"
		puts "temperature.label temperature"
		puts "temperature.info Temperature in degree Celsius"
		puts "temperature.type GAUGE"
	else
		puts "temperature.value #{temp}"
	end
end

echo_weather(data['id'], data['name'], data['main']['temp']-KELVIN_BIAS)
